site_name: SystemHack
theme:
  name: material

nav:
  - Estrategia de conversión:
      - Setting: setting.md
      - Closing: closing.md
      - Links y demás: links.md
  - Herramientas:
      - CRM y más: crm.md
  - Presentacion SystemHacks: presentacion.md

